### PR TITLE
Adding name to Certificate PDF's dynamically

### PR DESCRIPTION
**Pull request by cemrehancavdar**
We worked some on this treasure-hunt-app @Esri Türkiye. Actually, the nameless certificates bothered me.  Added ability to write name on it, by using pdf-lib.js library!

With, 3 more packages:
"pdf-lib",
"@pdf-lib/fontkit",
"downloadjs",

I've added a modifyPdf function to Utils.js and changed CongratsScreen.js by adding input, button and div with background to img.

If this PR acceptable, CongratsScreen.js may need a format document with your editor settings. 

Waiting for reviews and feedbacks :)

resim
resim

### CODE REVIEW

**Comment by leebock** [comment]
Hi cemrehancavdar!  This is a VERY cool enhancement that you have made.  I agree that the certificate is much more meaningful when it is personalized.  I'm sure that would delight our users!  I will share with you, however, there is a _possibility_ that we may be removing the certificate functionality entirely.  In our most recent design meetings, we actually discussed replacing the certificate with a more elaborate results screen which allows the users to share their score, etc.  

If we decide to keep the certificate, I will certainly give your PR a close review.  

In preparation for that eventuality, it would make the review process easier if could you could re-submit, making sure your workflow follows our contributing guidelines (below).

https://github.com/esri/contributing

Thanks again so much for your interest and your contributions!

Lee

**Comment by cemrehancavdar** [comment]
Hey, leebock! Thanks for your answer. Then let's keep PR open till new results screen. 😀

Secondly, i do a lot auto format when writing code and it adds unnecessary changes to code. Can you think about a basic prettier standart (a .prettierrc file)?

**Comment by leebock** [comment]
Hi cemrehancavdar!  The .prettierrc file sounds like a good idea.  I will be out office for most of the rest of this week, but I will look into it when I'm back next week.  Thanks!

**Comment by cemrehancavdar** [comment]
Closing PR due to change of replacing the certificate to new design.

**Pull request closed without merging**
